- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Medical
    min: 14400 #4 hrs
  - !type:CharacterEmployerRequirement
    employers:
    - ZengHuPharmaceuticals
    - Interdyne
    - NanoTrasen
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  - Paramedic
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 1.75

- type: startingGear
  id: DoctorGear
  subGear:
  - DoctorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    id: MedicalPDA
    ears: ClothingHeadsetMedical
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtMedicalDoctor
    satchel: ClothingBackpackSatchelMedicalFilled
    duffelbag: ClothingBackpackDuffelMedicalFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f

- type: startingGear
  id: DoctorPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMedicalDoctor
    head: ClothingHeadEnvirohelmMedicalDoctor
    gloves: ClothingHandsGlovesEnviroglovesWhite
