- type: job
  id: AcolyteSRM
  name: job-name-acolyte
  description: job-description-apprenticehunter
  playTimeTracker: JobAcolyteSRM
  weight: 1
  startingGear: AcolyteGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconAcolyte"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser

- type: startingGear
  id: AcolyteGear
  equipment:
    id: AcolytePDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunterAcolyte
    shoes: ClothingShoesBootsHunter
    gloves: ClothingHandsGlovesHunter
