- type: job
  id: AcolyteSRM
  name: job-name-acolyte
  description: job-description-apprenticehunter
  playTimeTracker: JobAcolyteSRM
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:FactionRequirement
      factionID: "SRM"
  weight: 22
  startingGear: AcolyteGear
  alwaysUseSpawner: true
  icon: "JobIconAcolyte"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: AcolyteGear
  equipment:
    id: AcolytePDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunterAcolyte
    shoes: ClothingShoesBootsHunter
    gloves: ClothingHandsGlovesHunter
