- type: job
  id: HunterSRM
  name: job-name-hunter
  description: job-description-hunter
  playTimeTracker: JobHunterSRM
  weight: 3
  startingGear: HunterGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconHunter"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterOverallTimeRequirement
      min: 20000
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: Telepathic

- type: startingGear
  id: HunterGear
  equipment:
    id: HunterPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunter
    head: ClothingHeadHatHunter
    shoes: ClothingShoesBootsHunter
    gloves: ClothingHandsGlovesHunter
