- type: job
  id: OverseerSRM
  name: job-name-overseer
  description: job-description-overseer
  playTimeTracker: JobOverseerSRM
  weight: 99
  startingGear: OverseerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconOverseer"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
  access:
  - Command
  - Hunter
  - HunterSenior
  - HunterOverseer
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: Telepathic

- type: startingGear
  id: OverseerGear
  equipment:
    id: OverseerPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitOverseer
    head: ClothingHeadHatHunterOverseer
    shoes: ClothingShoesBootsHunter
    outerClothing: ClothingOuterArmorHunterDusterOverseer
    gloves: ClothingHandsGlovesHunter
