- type: job
  id: TenderSRM
  name: job-name-tender
  description: job-description-tender
  playTimeTracker: JobTenderSRM
  weight: 2
  startingGear: TenderGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconTender"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: Telepathic
      - type: BibleUser
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 2

- type: startingGear
  id: TenderGear
  equipment:
    id: TenderPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunterAcolyte
    shoes: ClothingShoesBootsHunter
    head: ClothingHeadHatHunterTender
    outerClothing: ClothingOuterArmorHunterTender
    gloves: ClothingHandsGlovesHunter
    pocket1: RomaineBible
