- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-description-mail-carrier
  startingGear: CourierGear
  playTimeTracker: JobMailCarrier
  icon: "JobIconMailCarrier"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Mail

- type: startingGear
  id: MailCarrierGear
  subGear:
  - MailCarrierPlasmamanGear
  equipment:
    head: ClothingHeadMailCarrier
    jumpsuit: ClothingUniformMailCarrier
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: MailBag
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformSkirtMailCarrier
    satchel: ClothingBackpackSatchelFilled
    duffelbag: ClothingBackpackDuffelFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f

- type: startingGear
  id: MailCarrierPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMailCarrier
    head: ClothingHeadEnvirohelmMailCarrier
    gloves: ClothingHandsGlovesEnviroglovesWhite
