- type: job
  id: OperativeNCSP
  name: job-name-operative
  description: job-description-operative
  playTimeTracker: JobOperativeNCSP
  weight: 4
  startingGear: OperativeGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieOperative"
  supervisors: You answer to the patriach and the interests of the CyberDawn Technologies company.
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-operative
      - type: LanguageAdder
        addSpoken:
          - Freespeak
        addUnderstood:
          - Freespeak
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateRamzi
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: OperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSoldierCyberdawn
    shoes: ClothingShoesBootsCombat
    id: OperativePDA
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorKendoBogu
    ears: ClothingHeadsetNCSPCyberdawn
    back: ClothingBackpackNCSPFilledInfanteer
    belt: WeaponPistolHKUSP
