- type: job
  id: DeputyMarshalCMM
  name: job-name-deputymarshal
  description: job-description-deputymarshal
  playTimeTracker: JobDeputyMarshalCMM
  weight: 32
  startingGear: DeputyMarshalGear
  requirements:
  - !type:FactionRequirement
      factionID: "TSP"
  - !type:CharacterOverallTimeRequirement
    min: 36000
  - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-2ic
  alwaysUseSpawner: true
  icon: "JobIconDeputyMarshal"
  requireAdminNotify: false
  supervisors: You answer to your Colonial Marshal.
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - MinutemanRankingOfficer
  - MinutemanMarshal
  - CMMFunds
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DeputyMarshalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMDeputyMarshal
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    pocket1: WeaponRevolverSnubnose
    id: DeputyMarshalPDA
    ears: ClothingHeadsetCMM
    outerClothing: ClothingOuterArmorCMMDeputyCarapace
