- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PassengerGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtColorGrey
    satchel: ClothingBackpackSatchelFilled
    duffelbag: ClothingBackpackDuffelFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f

- type: startingGear
  id: PassengerPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitColorGrey
    head: ClothingHeadEnvirohelmColorGrey
    gloves: ClothingHandsGlovesEnviroglovesColorDarkGrey
