- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Epistemics
    min: 14400 # 4 hours - same as scientist
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: RoboticistGear
  subGear:
  - RoboticistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRoboticist
    back: ClothingBackpackRobotics
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatRobo
    id: RoboticsPDA
    ears: ClothingHeadsetRobotics
    pocket1: BookPsionicsGuidebook
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtRoboticist
    satchel: ClothingBackpackSatchelRoboticsFilled
    duffelbag: ClothingBackpackDuffelRoboticsFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f

- type: startingGear
  id: RoboticistPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitRoboticist
    head: ClothingHeadEnvirohelmRoboticist
    gloves: ClothingHandsGlovesEnviroglovesRoboticist
