- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Epistemics
    min: 14400 #4 hrs
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - ZengHuPharmaceuticals
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScience
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatRnd
    id: SciencePDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtScientist
    satchel: ClothingBackpackSatchelScienceFilled
    duffelbag: ClothingBackpackDuffelScienceFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f

- type: startingGear
  id: ScientistPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitScientist
    head: ClothingHeadEnvirohelmScientist
    gloves: ClothingHandsGlovesEnviroglovesWhite
