- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics
      min: 216000 #60 hrs
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: SeniorResearcherGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretRND
    jumpsuit: ClothingUniformJumpsuitSeniorResearcher
    back: ClothingBackpackScience
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtSeniorResearcher
    satchel: ClothingBackpackSatchelScienceFilled
    duffelbag: ClothingBackpackDuffelScienceFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f
