- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpsuitPirate
    satchel: ClothingBackpackPirateFilled
    duffelbag: ClothingBackpackPirateFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirate
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
    satchel: ClothingBackpackPirateFilled
    duffelbag: ClothingBackpackPirateFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f

- type: startingGear
  id: PirateFirstmateGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricorn
    outerClothing: ClothingOuterCoatGentle
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpsuitPirate
    satchel: ClothingBackpackPirateFilled
    duffelbag: ClothingBackpackPirateFilled
>>>>>>> 5756720415e76712123f53cbaa5f0f73193fba4f
