- type: job
  id: KapitanNCWL
  name: job-name-kapitan
  description: job-description-kapitan
  playTimeTracker: JobKapitanNCWL
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 50000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 25
  startingGear: KapitanGear
  alwaysUseSpawner: true
  icon: "JobIconCommsOfficer"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-kapitan
  access:
  - Command
  - Maintenance
  - Service
  - External
  - NCWLGeneral
  - NCWLJail
  - NCWLCommand
  - NCWLArmory
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: KapitanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWL
    id: KapitanPDA
    ears: ClothingHeadsetNCWL
    pocket1: WeaponPistolHKUSP
    outerClothing: ClothingOuterArmorNCWLCarapaceKapitan
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatNCWLBeret
