- type: job
  id: ConscriptDoctorNCWL
  name: job-name-conscript-ncwl-doctor
  description: job-description-conscript-ncwl-doctor
  playTimeTracker: ConscriptJobDoctorNCWL
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Blindness
        - WheelchairBound
  weight: 22
  startingGear: ConscriptDoctorNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconDoktor"
  requireAdminNotify: false
  supervisors: job-supervisors-conscript-ncwl
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-doctor
      - type: HullrotFaction
        faction: NCWL
  access:
  - Command
  - Maintenance
  - NCWLGeneral
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NCWLAdministrator
  - NCWLFunds
  - NCWLKommissar
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: ConscriptDoctorNCWLGear
  equipment:
    neck: ClothingNeckIFFOrange
    mask: ClothingMaskSterile
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    shoes: ClothingShoesBootsMagNCWL
    id: DoktorPDA
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltNCWLPouchesFilledMedic
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesNitrile
    pocket1: EmergencyOxygenTankFilled
    pocket2: ParamedHypo
    outerClothing: ClothingOuterArmorNCWLCarapaceDoktor
    head: ClothingHeadHatNCWLCapsoftMedical
    suitstorage: WeaponPistolT91
    back: ClothingBackpackSatchelMedical
  storage:
    back:
    - VoidsuitKitDSM
    - BoxMRE
    - BoxFlare
    - DefibrillatorCompact
    - MedkitCombatFilled
    - OmnizineChemistryBottle
    - Bloodpack
    - CartridgePuncturase
    - CartridgePuncturase
    - CartridgePuncturase
    - CartridgePuncturase
    - CartridgePuncturase
  inhand:
    - BookUnionfallNCWLGuide
    - CartridgePuncturase
